### ISSUE TITLE
Problem creating item

### ISSUE THREAD

**Issue by tramullas** [diegodlh/zotero-cita#108] opened 2021-06-01 09:45 UTC
Creating a new Wikidate item is a continuos problem, I can't get it workig... I copy my Zotero debug registry

[JavaScript Error: "WebSocket connection closed: 1006 "]

version => 5.0.96.2, platform => Linux x86_64, oscpu => Linux x86_64, locale => es-ES, appName => Zotero, appVersion => 5.0.96.2, extensions => Zotero LibreOffice Integration (5.0.25.SA.5.0.96.2, extension), Cita (0.2.3, extension)

(3)(+0094899): HTTP POST "queries=%7B%22q0%22%3A%7B%22query%22%3A%22Wikipedia%2C%20educaci%C3%B3n%20e%20informaci%C3%B3n%20cient%C3%ADfica%22%2C%22type%22%3A%22Q386724%22%2C%22type_strict%22%3A%22should%22%2C%22properties%22%3A%5B%7B%22pid%22%3A%22P356%22%2C%22v%22%3A%2210.3145%2FTHINKEPI.2018.50%22%7D%5D%7D%7D" to https://wikidata.reconci.link/en/api

(3)(+0000650): HTTP POST https://wikidata.reconci.link/en/api succeeded with 200

(4)(+0004006): Translate: Binding sandbox to http://www.example.com/

(3)(+0000003): Getting contents of /home/jesus/Zotero/translators/Wikidata QuickStatements.js

(4)(+0000006): Translate: Parsing code for Wikidata QuickStatements (51e5355d-9974-484f-80b9-f84d2b55782e, 2020-10-27 09:15:00)

(3)(+0000002): Translate: Beginning translation with Wikidata QuickStatements

(3)(+0000005): Translate: Translation successful

(5)(+0000000): Translate: Running handler 0 for done

(3)(+0030567): HTTP POST "queries=%7B%22q0%22%3A%7B%22query%22%3A%22Wikipedia%2C%20educaci%C3%B3n%20e%20informaci%C3%B3n%20cient%C3%ADfica%22%2C%22type%22%3A%22Q386724%22%2C%22type_strict%22%3A%22should%22%2C%22properties%22%3A%5B%7B%22pid%22%3A%22P356%22%2C%22v%22%3A%2210.3145%2FTHINKEPI.2018.50%22%7D%5D%7D%7D" to https://wikidata.reconci.link/en/api

(3)(+0000519): HTTP POST https://wikidata.reconci.link/en/api succeeded with 200

(4)(+0002578): Translate: Binding sandbox to http://www.example.com/

(3)(+0000003): Getting contents of /home/jesus/Zotero/translators/Wikidata QuickStatements.js

(4)(+0000007): Translate: Parsing code for Wikidata QuickStatements (51e5355d-9974-484f-80b9-f84d2b55782e, 2020-10-27 09:15:00)

(3)(+0000003): Translate: Beginning translation with Wikidata QuickStatements

(3)(+0000006): Translate: Translation successful

(5)(+0000000): Translate: Running handler 0 for done

(3)(+0020611): HTTP POST "queries=%7B%22q0%22%3A%7B%22query%22%3A%22Wikipedia%2C%20educaci%C3%B3n%20e%20informaci%C3%B3n%20cient%C3%ADfica%22%2C%22type%22%3A%22Q386724%22%2C%22type_strict%22%3A%22should%22%2C%22properties%22%3A%5B%7B%22pid%22%3A%22P356%22%2C%22v%22%3A%2210.3145%2FTHINKEPI.2018.50%22%7D%5D%7D%7D" to https://wikidata.reconci.link/en/api

(3)(+0000538): HTTP POST https://wikidata.reconci.link/en/api succeeded with 200

(4)(+0001676): Translate: Binding sandbox to http://www.example.com/

(3)(+0000003): Getting contents of /home/jesus/Zotero/translators/Wikidata QuickStatements.js

(4)(+0000018): Translate: Parsing code for Wikidata QuickStatements (51e5355d-9974-484f-80b9-f84d2b55782e, 2020-10-27 09:15:00)

(3)(+0000003): Translate: Beginning translation with Wikidata QuickStatements

(3)(+0000006): Translate: Translation successful

(5)(+0000001): Translate: Running handler 0 for done

**Comment by diegodlh** [comment] 2021-06-03 01:55
Hi, @tramullas! Thanks for reporting. Sorry that I couldn't reply earlier this week.

I will close this as I think it is a duplicate of #107. In short, I think it may be related to the library that converts QuickStatements commands into a format that `wikibase-edit` (the library in charge of automatic creation of new Wikidata items) can understand.

In the meantime, you can try using QuickStatements instead.

Unfortunately, automatic creation of new Wikidata items is possibly the most difficult part to test, because it implies actual creation of new (test) Wikidata items. This is not the case for creation of new "cites work" statements, because one can create those using Wikidata sandbox items for testing. Using [Wikidata's test instance](https://test.wikidata.org/) might be an option, but the problem is that all relevant properties have different PIDs than in the real Wikidata :/

**Comment by diegodlh** [comment] 2021-06-03 01:55
Duplicate of #107

**Closed by diegodlh** 2021-06-03 01:55 UTC
