### ISSUE TITLE
Ability to import an item from the citation tab

### ISSUE THREAD

**Issue by Futur3r** [diegodlh/zotero-cita#215] opened 2022-11-23 11:55 UTC
I would like to be able to import an item in my library from the citation tab of an article.

**Comment by Dominic-DallOsto** [comment] 2022-11-28 10:52
I think this makes a lot of sense!

Is what you would want essentially a shortcut for opening the citation, 
copying the DOI and pasting it into the "get item by identifier" bar in 
Zotero?

That should be quite straightforward. How it interacts with the linking 
of existing items in Zotero would be something to consider. But just to 
clarify the overall idea.

**Comment by diegodlh** [comment] 2022-11-28 14:56
I think this would be a duplicate of #40.

**Comment by Futur3r** [comment] 2022-11-28 18:03
Yes it is a duplicate of #40 :D
I didn't saw it before creating this issue, sorry !
While I'm at it, I want to add to also have the ability to add multiple citation items in a library, not just one by one.

**Closed** 2022-11-28 18:03 UTC
