### ISSUE TITLE
Remember WD username/password

### ISSUE THREAD

**Issue by VladimirAlexiev** [diegodlh/zotero-cita#194] opened 2022-10-17 14:08 UTC
Every time I want to create a WD item, the plugin asks for my username and password.
And because it's not a web page, the usual password managers (in my case google) cannot help me.
That is unbearable!

@diegodlh please fix this first!

Am I doing something wrong?

**Comment by diegodlh** [comment] 2022-10-17 14:50
Duplicate of #46

**Closed by diegodlh** 2022-10-17 14:50 UTC
