### ISSUE TITLE
Indicate Items in Zotero With Citations

### ISSUE THREAD

**Issue by LPILibrary** [diegodlh/zotero-cita#110] opened 2021-06-16 17:13 UTC
It is difficult to find the items in Zotero that have citations.

Some indicator or even a method to search and pull together all the items with citations would be helpful.

**Comment by diegodlh** [comment] 2021-06-17 15:18
Great suggestion! Thanks. There is an open issue to have extra columns for QID and citations. I'm gonna mark this as duplicate of that one.

**Comment by diegodlh** [comment] 2021-06-17 15:19
Duplicate of #23

**Closed by diegodlh** 2021-06-17 15:18 UTC
