### ISSUE TITLE
Store login information to avoid repeated logins when creating new items

### ISSUE THREAD

**Issue by cboulanger** [diegodlh/zotero-cita#198] opened 2022-10-20 10:28 UTC
**Is your feature request related to a problem? Please describe.**
Currently, when uploading a new item to WikiData, one has to re-enter one's credentials *each time*. This is very tedious and counter-productive (one gets frustrated pretty quickly). 

**Describe the solution you'd like**
CITA should cache the credentials data and automatically use it when reconnecting to WikiData

**Comment by Dominic-DallOsto** [comment] 2022-10-23 16:53
Duplicate of https://github.com/diegodlh/zotero-cita/issues/46

**Closed by Dominic-DallOsto** 2022-10-23 16:53 UTC
