### ISSUE TITLE
Fetching QIDs failed

### ISSUE THREAD

**Issue by cooketho** [diegodlh/zotero-cita#149] opened 2022-01-07 03:52 UTC
When I try to fetch QID for a zotero article with DOI 10.1038/370386A0, which should return Q42598957, cita says "Fetching QIDs ..." for several minutes, then returns the error message: "Fetching QIDs failed". I'm running

macOS Catalina 10.15.7
Zotero 5.0.96.3
cita 0.3.2

I tried with several other articles with the same result. Any help would be much appreciated! Thanks!

**Comment by Dominic-DallOsto** [comment] 2022-01-07 22:27
I was getting the following error response to the reconciliation query in Zotero

```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>502 Proxy Error</title>
</head><body>
<h1>Proxy Error</h1>
<p>The proxy server received an invalid
response from an upstream server.<br />
The proxy server could not handle the request<p>Reason: <strong>Error reading from remote server</strong></p></p>
<hr>
<address>Apache/2.4.38 (Debian) Server at wikidata.reconci.link Port 443</address>
</body></html>
```

I then checked in curl and the problem seems to be querying with certain types. For example, if I try to find [this](https://www.wikidata.org/wiki/Q74430325) item, everything works fine if I specify the actual type (scholarly article):

```bash
curl -X POST -F 'queries={"q0":{"query":"Parton distributions of the proton","type":"Q13442814"}}' https://wikidata.reconci.link/en/api
```

Working up the type hierarchy, it also works if I specify article (Q191067), written work (Q47461344), creative work (Q17537576) or intellectual work (Q15621286), but doesn't work if I specify the type work (Q386724).

In this case I get the following error message.

```bash
curl -X POST -F 'queries={"q0":{"query":"Parton distributions of the proton","type":"Q386724"}}' https://wikidata.reconci.link/en/api

{"arguments":{"lang":"en","queries":"{\"q0\":{\"query\":\"Parton distributions of the proton\",\"type\":\"Q386724\"}}"},"details":"Invalid control character at: line 5796829 column 74 (char 139001879)","message":"invalid query","status":"error"}
```

The problem is that Cita uses work as the base type when running reconciliation to find item QIDs, and so you're getting this error. Changing the base type to creative work seems to fix it, but it's not clear why.

**Closed** 2022-01-14 11:43 UTC
Labels: bug
