### ISSUE TITLE
Multiple conference papers with same ISBN

### ISSUE THREAD

**Issue by Dominic-DallOsto** [diegodlh/zotero-cita#159] opened 2022-02-03 13:27 UTC
A bit of an odd/specific issue I just encountered.

For conference papers Cita stores the DOI and ISBN. I'm not sure how widespread this is, but at least in some IEEE conferences each paper in the proceedings has its own DOI, but all share the same ISBN.

If I have an item that happens to cite two papers from the same conference (eg. [this](https://doi.org/10.1109/IROS45743.2020.9341670) and [this](https://doi.org/10.1109/IROS45743.2020.9341100)) and add them as citation (by DOI for example), everything works fine. But then if I edit either of these items I can't save it because the ISBN is in use by another item.

The only workaround for me at the moment was to remove the ISBN from at least one of the items. 

I'm not sure what the best way to deal with this might be though? Could we allow duplicate ISBNs for items that also have a DOI? 

I guess a similar issue might come up when addressing #37

**Comment by diegodlh** [comment] 2022-02-07 00:23
Nice finding.

I think the way to go may be just ignoring ISBNs for book chapters and conference papers, as suggested in #102.

I'll close this as duplicate of #102, and briefly mention the additional undesired outcome you mention here.

**Comment by diegodlh** [comment] 2022-02-07 00:23
Duplicate of #102

**Closed by diegodlh** 2022-02-07 00:23 UTC
Labels: bug
