### ISSUE TITLE
Citations sidebar pane empty

### ISSUE THREAD

**Issue by drewx0r** [diegodlh/zotero-cita#254] opened 2023-04-26 18:30 UTC
**Describe the bug**
The Citations tab in the sidebar doesn't show anything. It is completely blank with no objects at all in the pane below the tab bar (but the citations are still stored in a note)

**To Reproduce**
Click any item in the central pane
Select the Citations tab in the right sidebar

**Expected behavior**
Previously, a list of citations would show up

**Environment:**
 - Zotero version: 6.0.26
 - Cita version: 0.5.5
 - OS name and version: macOS Ventura 13.3.1

**Additional context**
I have disabled all addons except for Cita and Better BibTex for Zotero

**Comment by drewx0r** [comment] 2023-04-26 18:54
I forgot to include the debug log info. Here's what pops up when I click the citations tab:

```
(3)(+0002248): Viewing item in pane 5

(3)(+0000008): {Cita} Wed Apr 26 2023 13:52:39 GMT-0500 (CDT): Refreshing citations pane... (zotero-editpane-tabs)

(3)(+0000005): {Cita} Wed Apr 26 2023 13:52:39 GMT-0500 (CDT): CitationsBoxContainer will render...

(3)(+0000024): {Cita} Wed Apr 26 2023 13:52:39 GMT-0500 (CDT): Getting citations from source item took 21.207457999698818
```

But nothing is rendering

**Comment by drewx0r** [comment] 2023-04-27 01:38
I get this message in the Error Console when I select the Cita tab:

```
[JavaScript Error: "Error: Localized string not available for More..." {file: "chrome://zotero/content/xpcom/intl.js" line: 137}]
Zotero.Intl</this.getString@chrome://zotero/content/xpcom/intl.js:137:15
this.getString@chrome://zotero/content/xpcom/zotero.js:1323:34
get text@chrome://zotero/content/components/button.js:134:340
render@chrome://zotero/content/components/button.js:137:5
finishClassComponent@chrome://cita/content/main.js:29775:22
updateClassComponent@chrome://cita/content/main.js:29725:24
beginWork@chrome://cita/content/main.js:31363:16
callCallback@chrome://cita/content/main.js:16235:9
invokeGuardedCallbackDev@chrome://cita/content/main.js:16284:7
invokeGuardedCallback@chrome://cita/content/main.js:16346:3
beginWork$1@chrome://cita/content/main.js:36249:7
performUnitOfWork@chrome://cita/content/main.js:35064:12
workLoopSync@chrome://cita/content/main.js:34992:5
renderRootSync@chrome://cita/content/main.js:34955:7
performSyncWorkOnRoot@chrome://cita/content/main.js:34578:18
./node_modules/react-dom/cjs/react-dom.development.js/flushSyncCallbackQueueImpl/<@chrome://cita/content/main.js:23617:26
unstable_runWithPriority@chrome://cita/content/main.js:41996:12
runWithPriority$1@chrome://cita/content/main.js:23566:10
flushSyncCallbackQueueImpl@chrome://cita/content/main.js:23612:9
flushSyncCallbackQueue@chrome://cita/content/main.js:23599:3
scheduleUpdateOnFiber@chrome://cita/content/main.js:34178:9
updateContainer@chrome://cita/content/main.js:37767:3
legacyRenderSubtreeIntoContainer@chrome://cita/content/main.js:38322:5
render@chrome://cita/content/main.js:38388:10
refreshCitationsPane@chrome://cita/content/main.js:6761:9
refreshCitationsPane@chrome://cita/content/main.js:6121:3
set_selectedIndex@chrome://global/content/bindings/tabbox.xml:395:15
set_selectedItem@chrome://global/content/bindings/tabbox.xml:420:34
_selectNewTab@chrome://global/content/bindings/tabbox.xml:465:11
onxblmousedown@chrome://global/content/bindings/tabbox.xml:762:11
```

**Comment by Dominic-DallOsto** [comment] 2023-04-27 08:23
Thanks a lot! This seems to definitely be a duplicate of #247 

Interesting to here it also happens on Mac though.

**Closed by Dominic-DallOsto** 2023-04-27 08:23 UTC
